### ISSUE TITLE
Adding BEP-20 Support

### ISSUE THREAD

**Issue by matissime** [vittominacori/watch-token#4]
Hello, can you add the Binance Smart Chain in the Network List ?
Thanks.

**Comment by vittominacori** [comment]
Yes, it is scheduled. Will let you know when ready.

**Comment by vittominacori** [comment]
Hi, added BSC 

Try it https://vittominacori.github.io/watch-token/create/?network=bsc_mainnet

**Comment by matissime** [comment]
Nice work ! very cool, thanks :D
