### ISSUE TITLE
Seems like the new generated bep20 links aint working ? 

### ISSUE THREAD

**Issue by chineselegend** [vittominacori/watch-token#6]
Hi, I just generated this link https://vittominacori.github.io/watch-token/page/?hash=0x7b2261646472657373223a22307865663033324636353246434533613065466663653337393641363865623937386234363561333336222c226c6f676f223a2268747470733a2f2f692e696d6775722e636f6d2f7431683243634d2e706e67227d&network=bsc_mainnet but it seems like its no adding it to metamask, but its detecting that its on other network, any ideas how we could fix that ? 🥇

**Comment by vittominacori** [comment]
Hi, try switching network to Binance Mainnet as described here https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain

After switching network reload the page and try again.
