### ISSUE TITLE
Error: No provider selected for request eth_chainId

### ISSUE THREAD

**Issue by Contract-QA** [vittominacori/watch-token#7]
![image](https://user-images.githubusercontent.com/84654194/121285395-57ecd100-c8ac-11eb-972f-6feae4a16913.png)

This error keeps occuring when trying to create a widget for either mainnet (eth or bnb)

https://vittominacori.github.io/watch-token/page/?hash=0x7b2261646472657373223a22307838303736633734633565336635383532303337663331666630303933656562386338616464386433222c226c6f676f223a22227d&network=bsc_mainnet

**Comment by vittominacori** [comment]
Hello, try adding bsc mainnet provider following this https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain

**Comment by Contract-QA** [comment]
I am trying to do an erc20 token (just happened to also try a bnb one as well to see) do i still need to add this provider in order for the erc20 widget to work as well?
