### ISSUE TITLE
Error: Cannot find module './.env.json'

### ISSUE THREAD

**Issue by damianlluch** [vittominacori/watch-token#8]
Hi! thanks for shared your work.
I get his error when I try execute.

damian@damian-Latitude-7400:~/Documents/work/watch-token$ npm run dev

> watch-token@1.0.0 dev /home/damian/Documents/work/watch-token
> vuepress dev

wait Extracting site metadata...
Error: Cannot find module './.env.json'

**Comment by hlooman** [comment]
In the .vuepress folder there's a .env.json.example file, use that one to create a .env.json file with your own settings
